//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public string Id_Office { get; set; }
        public string Name_Office { get; set; }
        public string Manager { get; set; }
    }
}
